//used ="['"&A2&"', '"&B2&"', '"&C2&"', '"&D2&"', '"&E2&"']," on the google sheets database
//ID	Title	Description	Connections	Possible Encounters
const ZoneTechnologyIsland = [
  [
    "1",
    "Dock",
    "A Simple dock, peaceful sea.",
    "2, 3, 4, 5",
    "Sirens, Sea-serpent, Nothing",
  ],
  [
    "2",
    "Under the Dock",
    "Exploring under the dock.",
    "1",
    "Sirens, Sea-serpent, Treasure, Rotted Corpse, Lootable Corpse, Nothing",
  ],
  [
    "3",
    "Storage room",
    "Storage for boat equipment.",
    "1, 4, 5",
    "Ship loot, Naked Bodies, Clothed Bodies, Nothing",
  ],
  ["4", "Cabin one", "Cabin with an automata.", "1, 3, 5", "Automata"],
  [
    "5",
    "Cabin two",
    "Spacious cabin with a mirror.",
    "4, 6",
    "Ghostly Apparition, Forgotten Diary, Hidden Compartment, Nothing",
  ],
  [
    "6",
    "Cabin three",
    "Cabin in disarray, hints at a struggle.",
    "5, 7, 8, 9",
    "Wounded Survivor, Clues to a Conspiracy, Nothing",
  ],
  [
    "7",
    "Cabin Four",
    "Locked cabin with muffled sounds.",
    "5, 6, 8, 9",
    "Spider Trap, Underground Mine",
  ],
  ["8", "Structure", "Location of the last fight.", "-", "-"],
  [
    "9",
    "Jungle fall",
    "Hidden waterfall in the dense jungle.",
    "10, 11, 8",
    "Hero Falls down, Nothing",
  ],
  [
    "10",
    "Jungle one",
    "Dense jungle with teeming wildlife.",
    "9, 11",
    "Elktiger, Spiders, Poisonous Plants, Mysterious Altar, Nothing",
  ],
  [
    "11",
    "Jungle two",
    "Mysterious jungle with ancient ruins.",
    "9, 10",
    "Lost Explorer, Cursed Relic, Booby Traps, Ambush by Jungle Inhabitants, Owlbear, Wolf pack",
  ],
];

const ZoneWaterfallIsland = [
  [
    "1",
    "Waterside Grotto",
    "A secluded grotto by the island.s shore.",
    "2, 3, 4, 5",
    "Nymphs, Underwater Cavern, Sunken Treasure",
  ],
  [
    "2",
    "Behind the Falls",
    "A hidden passage behind the waterfall.",
    "1, 6",
    "Mysterious Runes, Hidden Fae Enclave",
  ],
  [
    "3",
    "Flowering Glen",
    "A meadow filled with vibrant, otherworldly plants.",
    "1, 5, 7",
    "Treant Guardian, Talking Butterflies",
  ],
  [
    "4",
    "Ancient Tree of Whispers",
    "A colossal tree with ancient knowledge.",
    "1, 5, 8",
    "Wise Tree Guardian, Eavesdropping Spirits",
  ],
  [
    "5",
    "Crystal Cove",
    "A cove with luminescent crystals.",
    "1, 3, 4, 9",
    "Crystal Guardians, Reflection Pools",
  ],
  [
    "6",
    "Fae.s Playground",
    "A glade filled with playful fae creatures.",
    "2, 10",
    "Riddle-Spouting Pixies, Fey Challenges",
  ],
  [
    "7",
    "Enchanted Pool",
    "A serene pool with magical properties.",
    "3, 11",
    "Water Nymphs, Healing Springs",
  ],
  [
    "8",
    "Hidden Library",
    "A labyrinthine library with ancient knowledge.",
    "4, 11, 12",
    "Guardian Sphinx, Lost Lore",
  ],
  [
    "9",
    "Mystical Gorge",
    "A place of potent magic within the island.",
    "5, 10, 13",
    "Etheral Mist, Elemental Beings",
  ],
  [
    "10",
    "Luminous Glade",
    "A glade with bioluminescent plants and creatures.",
    "6, 9, 14",
    "Time-Warping Fauna, Memory Vortex",
  ],
  [
    "11",
    "Elemental Nexus",
    "A place where elemental forces converge.",
    "7, 8, 15",
    "Elemental Guardians, Balance Trials",
  ],
  [
    "12",
    "Forgotten Altar",
    "A long-forgotten altar dedicated to ancient deities.",
    "8, 15",
    "Divine Presence, Blessing or Curse",
  ],
  [
    "13",
    "Echoing Abyss",
    "A chasm with echoing whispers.",
    "9, 14, 16",
    "Abyssal Guardian, Lost Souls",
  ],
  [
    "14",
    "Twilight Grove",
    "A grove at the bottom of the chasm with twilight.",
    "10, 13, 17",
    "Time-Bending Creatures, Ethereal Anomalies",
  ],
  [
    "15",
    "Nexus of Realities",
    "A place where dimensions blur.",
    "11, 12",
    "Interdimensional Beings, Reality Shifting",
  ],
  [
    "16",
    "Crystalheart Chamber",
    "A crystalline chamber at the heart of the island.",
    "13, 17",
    "Crystalheart Guardian, Resonating Energy",
  ],
  [
    "17",
    "The Heart of the Island",
    "The epicenter of the island.s magic and ultimate challenge.",
    "None",
    "Island Guardian, Dimensional Rift",
  ],
];
const ZoneAbandonedIsland = [];
const ZoneHellIsland = [
  [
    "1",
    "Sea of corpes",
    "A desolate, fiery beach.",
    "2, 3, 4",
    "Scorching Sand, Infernal Waves, Tentacle Beasts, Nothing",
  ],
  [
    "2",
    "Volcanic Caves",
    "Dark caves filled with molten rock.",
    "1, 3, 5",
    "Lava Flows, Fire Elementals, Molten Treasure, Nothing",
  ],
  [
    "3",
    "Cursed Forest",
    "A forest consumed by hellish flames.",
    "1, 2, 6",
    "Demon Bats, Charred Trees, Lost Souls, Nothing",
  ],
  [
    "4",
    "Lava Pits",
    "Expansive pits of bubbling lava.",
    "1, 7, 8",
    "Fire Sprites, Lava Golems, Precious Gems, Nothing",
  ],
  [
    "5",
    "Hellish Caverns",
    "Caverns with eerie red-glowing crystals.",
    "2, 9, 10",
    "Sinister Shadows, Crystal Geodes, Hellfire Runes, Nothing",
  ],
  [
    "6",
    "Abyssal Swamp",
    "A swamp where the waters burn.",
    "3, 11, 12",
    "Demon Frogs, Cursed Marshes, Soul-Tormented Beasts, Nothing",
  ],
  [
    "7",
    "Obsidian Bridge",
    "A bridge over a river of molten rock.",
    "4, 13, 14",
    "Lava Guardians, Volcanic Eruptions, Bridge Collapse, Nothing",
  ],
  [
    "8",
    "Infernal Peaks",
    "Jagged peaks with hellish storms.",
    "4, 15, 16",
    "Hellfire Thunder, Demon Raptors, Tempest Chaos, Nothing",
  ],
  [
    "9",
    "Fiery Chasm",
    "A deep chasm spewing flames.",
    "5, 17, 18",
    "Flame-Winged Fiends, Fiery Abyss, Infernal Echoes, Nothing",
  ],
  [
    "10",
    "Demonic Shrine",
    "A shrine to infernal deities.",
    "5, 19",
    "Dark Rituals, Infernal Offerings, Cursed Artifacts, Nothing",
  ],
  [
    "11",
    "Charred Ruins",
    "Ruined structures engulfed in fire.",
    "6, 20",
    "Ashen Ghosts, Eerie Relics, Fiery Remnants, Nothing",
  ],
  [
    "12",
    "Gates of Hell",
    "The entrance to the realm.s core.",
    "6",
    "Infernal Guardians, Soul-Consuming Flames, Cursed Portal, Nothing",
  ],
  [
    "13",
    "Volcanic Heart",
    "The fiery heart of the island.",
    "7",
    "Magma Elemental, Lava Crystals, Eternal Inferno, Nothing",
  ],
  [
    "14",
    "Hellish Crossroads",
    "A junction of infernal paths.",
    "7",
    "Demon Wraiths, Infernal Whispers, Fiery Decisions, Nothing",
  ],
  [
    "15",
    "Abyssal Storm",
    "A storm with scorching winds.",
    "8",
    "Tempest Spirits, Infernal Cyclones, Lightning Strikes, Nothing",
  ],
  [
    "16",
    "Inferno.s Eye",
    "A fiery vortex of chaotic energy.",
    "8",
    "Chaos Demons, Flame Tornadoes, Blazing Anomalies, Nothing",
  ],
  [
    "17",
    "Flame-Wrapped Abyss",
    "A treacherous abyss engulfed in flames.",
    "9",
    "Infernal Serpents, Eternal Flames, Abyssal Treasures, Nothing",
  ],
  [
    "18",
    "Infernal Forge",
    "A cursed forge where weapons are made.",
    "9",
    "Forge Guardians, Cursed Blades, Infernal Smiths, Nothing",
  ],
  [
    "19",
    "Temple of Torment",
    "A temple dedicated to pain and suffering.",
    "10",
    "Torment Priests, Agonizing Rituals, Hellish Offerings, Nothing",
  ],
  ["20", "The Hellish Overlord", "The ruler of Hell Island.", "-", "-"],
];
const ZoneHuntIsland = [
  [
    "1",
    "Beach",
    "A sandy beach with the sound of waves.",
    "2, 3, 4",
    "Crabs, Shimmering Shells, Nothing",
  ],
  [
    "2",
    "Jungle",
    "Dense jungle teeming with wildlife.",
    "1, 3, 6, 7",
    "Jaguars, Poisonous Snakes, Mysterious Plants, Nothing",
  ],
  [
    "3",
    "River Crossing",
    "A fast-flowing river cuts through the jungle.",
    "5",
    "Crocodiles, Rickety Bridge, Swirling Whirlpool, Lost Map, Nothing",
  ],
  [
    "4",
    "Campsite",
    "A makeshift campsite with abandoned supplies.",
    "1, 5, 8, 9",
    "Traps, Wildlife Tracks, Abandoned Journal, Nothing",
  ],
  [
    "5",
    "Waterfall",
    "A majestic waterfall with a serene pool.",
    "4, 10, 11",
    "Hidden Cave, Water Spirits, Precious Gem, Dangerous Current, Nothing",
  ],
  [
    "6",
    "Ancient Temple",
    "A mysterious temple deep in the jungle.",
    "2, 7, 10, 12",
    "Tribal Guardians, Booby Traps, Amazing Animal, Ancient Relic, Nothing",
  ],
  [
    "7",
    "Swamp",
    "A murky swamp with eerie sounds.",
    "2, 6, 8, 13",
    "Mud Creatures, Quicksand, Haunting Whispers, Forgotten Treasure, Nothing",
  ],
  [
    "8",
    "Abandoned Hut",
    "A dilapidated hut in the middle of the swamp.",
    "4, 7, 9, 12",
    "Ghostly Apparition, Voodoo Altar, Cursed Artefact, Mysterious Potion, Nothing",
  ],
  [
    "9",
    "Dark Forest",
    "A dense, ominous forest with towering trees.",
    "4, 8, 11, 12",
    "Shadowy Figures, Lost Path, Enchanted Grove, Amazing Animal, Nothing",
  ],
  [
    "10",
    "Volcano Crater",
    "An active volcano with rumbling lava.",
    "5, 6, 11, 12",
    "Lava Flows, Fiery Creatures, Amazing Animal, Ancient Cavern, Eruption Warning, Nothing",
  ],
  [
    "11",
    "Cliff Overlook",
    "A high cliff offering a panoramic view.",
    "9, 10, 12",
    "Gliding Raptors, Hidden Treasure, Rare Plants, Amazing Animal, Nothing",
  ],
  [
    "12",
    "Abandoned Village",
    "A deserted village with overgrown buildings.",
    "6, 8, 9, 10, 11, 13",
    "Vengeful Spirits, Tribal Relics, Cursed Ground, Lost Secrets, Nothing",
  ],
  ["13", "La Pampa", "A place for the delight of the hunter god.", "-", "-"],
];
